### PR TITLE
New Google+ icon and updated character mapping references

### PR DESCRIPTION
**Pull request by jon-dodd**
The icon set was still using the old G+ logomark and I needed the new one for a project, so have updated here too.

### CODE REVIEW

**Comment by cshold** [comment]
Can you size the new icon a bit better. I bumped the font-size up a bit in your branch so you can see that it's off compared to the rest.

screen shot 2015-11-10 at 11 49 16 am

**Comment by jon-dodd** [comment]
Ah yes does look a bit small there. On my custom job is was find but I'd changed other bits elsewhere. Will swap out the SVG for a bigger one :)

**Comment by jon-dodd** [comment]
Have now pushed up a new commit which should be a similar size, so if you wanted to have a look and use as you wish :)

**Comment by cshold** [comment]
Still looks off to me. Maybe IcoMoon handles sizes differently than Fontastic?

**Pull request merged**
